services:

  radiko:
    build: .
    image: "${APP}_radiko:${TAG}"
    volumes:
      - type: volume
        source: FILES_DIR
        target: /files
        read_only: false
    environment:
        - CLOUDFLARE_BUCKET_NAME
        - CLOUDFLARE_ACCOUNT_ID
        - CLOUDFLARE_ACCESS_KEY_ID
        - CLOUDFLARE_SECRET_ACCESS_KEY
        - QUEUE_URL
        - QUEUE_USERNAME
        - QUEUE_SECRET_KEY
        - SLACK_WEBHOOK_URL
        - IS_PRODUCTION
        - SENTRY_DSN

volumes:
  FILES_DIR:
