version: "3.2"
services:

  feeder:
    build: ./feeder
    volumes:
      - type: volume
        source: FEEDER_SOCKET_DIR
        target: /app/logs
        read_only: false
      - type: volume
        source: PUBLIC_DIR
        target: /public
        read_only: true

  nginx:
    build: ./nginx
    ports:
      - 8082:80
    volumes:
      - type: volume
        source: FEEDER_SOCKET_DIR
        target: /var/run/feeder
        read_only: false
      - type: volume
        source: PUBLIC_DIR
        target: /public/mp3
        read_only: true

  batch:
    build: ./batch
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public
        read_only: false

volumes:
  FEEDER_SOCKET_DIR:
  PUBLIC_DIR:

