version: "3.2"
services:

  feeder:
    build: ./feeder
    image: "${APP}_feeder:${TAG}"
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public
        read_only: true
    environment:
        - USER
        - PASSWORD

  nginx:
    build: ./nginx
    image: "${APP}_nginx:${TAG}"
    ports:
      - 8082:80
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public/mp3
        read_only: true

  batch:
    image: "${APP}_batch:${TAG}"
    build:
      dockerfile: ./batch/Dockerfile
      context: .
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public
        read_only: false
    environment:
        - SLACK_WEBHOOK_URL

  timefree:
    build:
      dockerfile: ./timefree/Dockerfile
      context: .
    image: "${APP}_timefree:${TAG}"
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public
        read_only: false
    environment:
        - SQS_URL
        - DEAD_LETTER_SQS_URL
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - SLACK_WEBHOOK_URL

volumes:
  PUBLIC_DIR:
