version: "3.2"
services:

  feeder:
    build: ./feeder
    ports:
      - 8081:8080
    volumes:
      - type: volume
        source: FEEDER_SOCKET_DIR
        target: /app/logs
      - type: volume
        source: PUBLIC_DIR
        target: /public

  nginx:
    build: ./nginx
    ports:
      - 8082:80
    volumes:
      - type: volume
        source: FEEDER_SOCKET_DIR
        target: /var/run/feeder
      - type: volume
        source: PUBLIC_DIR
        target: /public/mp3

  batch:
    build: ./batch
    volumes:
      - type: volume
        source: PUBLIC_DIR
        target: /public

volumes:
  FEEDER_SOCKET_DIR:
  PUBLIC_DIR:

