version: "3.2"
services:

  feeder:
    build: ./feeder
    ports:
      - 8081:8080
    volumes:
      - type: volume
        source: FEEDER_LOGS
        target: /app/logs
      - type: volume
        source: PUBLIC_DIR
        target: /public

  nginx:
    build: ./nginx
    ports:
      - 8082:80
    volumes:
      - type: volume
        source: FEEDER_LOGS
        target: /var/run/feeder
      - type: volume
        source: PUBLIC_DIR
        target: /work/public

volumes:
  FEEDER_LOGS:
  PUBLIC_DIR:

